// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaO-DjZPhbU9j_JMMW43v-HNPJAnV2PjA',
    appId: '1:933224625617:web:7f7f1c9bae216281f4dcf0',
    messagingSenderId: '933224625617',
    projectId: 'whatsapp-clone-2bfd0',
    authDomain: 'whatsapp-clone-2bfd0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-2bfd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBn0Ubg6etMHknFztFcHN1ArMlBgyS2o',
    appId: '1:933224625617:android:a9547c132db862fbf4dcf0',
    messagingSenderId: '933224625617',
    projectId: 'whatsapp-clone-2bfd0',
    storageBucket: 'whatsapp-clone-2bfd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFn3eGuQ2knHm7mlKn4XBAlpSi6JKgMh0',
    appId: '1:933224625617:ios:2b8b968e92c5579df4dcf0',
    messagingSenderId: '933224625617',
    projectId: 'whatsapp-clone-2bfd0',
    storageBucket: 'whatsapp-clone-2bfd0.appspot.com',
    iosBundleId: 'com.example.myWhatsaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFn3eGuQ2knHm7mlKn4XBAlpSi6JKgMh0',
    appId: '1:933224625617:ios:43c78c2d3d02af17f4dcf0',
    messagingSenderId: '933224625617',
    projectId: 'whatsapp-clone-2bfd0',
    storageBucket: 'whatsapp-clone-2bfd0.appspot.com',
    iosBundleId: 'com.example.myWhatsaap.RunnerTests',
  );
}








// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );